//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WS_Negocios.WS_Datos_User {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Personas", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Personas : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IDField;
        
        private int ID_UsuariosField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ApellidosField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CorreoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string telefonoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int ID_Usuarios {
            get {
                return this.ID_UsuariosField;
            }
            set {
                if ((this.ID_UsuariosField.Equals(value) != true)) {
                    this.ID_UsuariosField = value;
                    this.RaisePropertyChanged("ID_Usuarios");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Apellidos {
            get {
                return this.ApellidosField;
            }
            set {
                if ((object.ReferenceEquals(this.ApellidosField, value) != true)) {
                    this.ApellidosField = value;
                    this.RaisePropertyChanged("Apellidos");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string Correo {
            get {
                return this.CorreoField;
            }
            set {
                if ((object.ReferenceEquals(this.CorreoField, value) != true)) {
                    this.CorreoField = value;
                    this.RaisePropertyChanged("Correo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string telefono {
            get {
                return this.telefonoField;
            }
            set {
                if ((object.ReferenceEquals(this.telefonoField, value) != true)) {
                    this.telefonoField = value;
                    this.RaisePropertyChanged("telefono");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WS_Datos_User.DatosSoap")]
    public interface DatosSoap {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento personas del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/insertar", ReplyAction="*")]
        WS_Negocios.WS_Datos_User.insertarResponse insertar(WS_Negocios.WS_Datos_User.insertarRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/insertar", ReplyAction="*")]
        System.Threading.Tasks.Task<WS_Negocios.WS_Datos_User.insertarResponse> insertarAsync(WS_Negocios.WS_Datos_User.insertarRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento personas del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/modificar", ReplyAction="*")]
        WS_Negocios.WS_Datos_User.modificarResponse modificar(WS_Negocios.WS_Datos_User.modificarRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/modificar", ReplyAction="*")]
        System.Threading.Tasks.Task<WS_Negocios.WS_Datos_User.modificarResponse> modificarAsync(WS_Negocios.WS_Datos_User.modificarRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento EliminarResult del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Eliminar", ReplyAction="*")]
        WS_Negocios.WS_Datos_User.EliminarResponse Eliminar(WS_Negocios.WS_Datos_User.EliminarRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Eliminar", ReplyAction="*")]
        System.Threading.Tasks.Task<WS_Negocios.WS_Datos_User.EliminarResponse> EliminarAsync(WS_Negocios.WS_Datos_User.EliminarRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento MostrarResult del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Mostrar", ReplyAction="*")]
        WS_Negocios.WS_Datos_User.MostrarResponse Mostrar(WS_Negocios.WS_Datos_User.MostrarRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Mostrar", ReplyAction="*")]
        System.Threading.Tasks.Task<WS_Negocios.WS_Datos_User.MostrarResponse> MostrarAsync(WS_Negocios.WS_Datos_User.MostrarRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento BuscarResult del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Buscar", ReplyAction="*")]
        WS_Negocios.WS_Datos_User.BuscarResponse Buscar(WS_Negocios.WS_Datos_User.BuscarRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Buscar", ReplyAction="*")]
        System.Threading.Tasks.Task<WS_Negocios.WS_Datos_User.BuscarResponse> BuscarAsync(WS_Negocios.WS_Datos_User.BuscarRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class insertarRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="insertar", Namespace="http://tempuri.org/", Order=0)]
        public WS_Negocios.WS_Datos_User.insertarRequestBody Body;
        
        public insertarRequest() {
        }
        
        public insertarRequest(WS_Negocios.WS_Datos_User.insertarRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class insertarRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WS_Negocios.WS_Datos_User.Personas personas;
        
        public insertarRequestBody() {
        }
        
        public insertarRequestBody(WS_Negocios.WS_Datos_User.Personas personas) {
            this.personas = personas;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class insertarResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="insertarResponse", Namespace="http://tempuri.org/", Order=0)]
        public WS_Negocios.WS_Datos_User.insertarResponseBody Body;
        
        public insertarResponse() {
        }
        
        public insertarResponse(WS_Negocios.WS_Datos_User.insertarResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class insertarResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string insertarResult;
        
        public insertarResponseBody() {
        }
        
        public insertarResponseBody(string insertarResult) {
            this.insertarResult = insertarResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class modificarRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="modificar", Namespace="http://tempuri.org/", Order=0)]
        public WS_Negocios.WS_Datos_User.modificarRequestBody Body;
        
        public modificarRequest() {
        }
        
        public modificarRequest(WS_Negocios.WS_Datos_User.modificarRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class modificarRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WS_Negocios.WS_Datos_User.Personas personas;
        
        public modificarRequestBody() {
        }
        
        public modificarRequestBody(WS_Negocios.WS_Datos_User.Personas personas) {
            this.personas = personas;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class modificarResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="modificarResponse", Namespace="http://tempuri.org/", Order=0)]
        public WS_Negocios.WS_Datos_User.modificarResponseBody Body;
        
        public modificarResponse() {
        }
        
        public modificarResponse(WS_Negocios.WS_Datos_User.modificarResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class modificarResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string modificarResult;
        
        public modificarResponseBody() {
        }
        
        public modificarResponseBody(string modificarResult) {
            this.modificarResult = modificarResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class EliminarRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Eliminar", Namespace="http://tempuri.org/", Order=0)]
        public WS_Negocios.WS_Datos_User.EliminarRequestBody Body;
        
        public EliminarRequest() {
        }
        
        public EliminarRequest(WS_Negocios.WS_Datos_User.EliminarRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class EliminarRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int id;
        
        public EliminarRequestBody() {
        }
        
        public EliminarRequestBody(int id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class EliminarResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="EliminarResponse", Namespace="http://tempuri.org/", Order=0)]
        public WS_Negocios.WS_Datos_User.EliminarResponseBody Body;
        
        public EliminarResponse() {
        }
        
        public EliminarResponse(WS_Negocios.WS_Datos_User.EliminarResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class EliminarResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string EliminarResult;
        
        public EliminarResponseBody() {
        }
        
        public EliminarResponseBody(string EliminarResult) {
            this.EliminarResult = EliminarResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class MostrarRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Mostrar", Namespace="http://tempuri.org/", Order=0)]
        public WS_Negocios.WS_Datos_User.MostrarRequestBody Body;
        
        public MostrarRequest() {
        }
        
        public MostrarRequest(WS_Negocios.WS_Datos_User.MostrarRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class MostrarRequestBody {
        
        public MostrarRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class MostrarResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="MostrarResponse", Namespace="http://tempuri.org/", Order=0)]
        public WS_Negocios.WS_Datos_User.MostrarResponseBody Body;
        
        public MostrarResponse() {
        }
        
        public MostrarResponse(WS_Negocios.WS_Datos_User.MostrarResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class MostrarResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WS_Negocios.WS_Datos_User.Personas[] MostrarResult;
        
        public MostrarResponseBody() {
        }
        
        public MostrarResponseBody(WS_Negocios.WS_Datos_User.Personas[] MostrarResult) {
            this.MostrarResult = MostrarResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class BuscarRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Buscar", Namespace="http://tempuri.org/", Order=0)]
        public WS_Negocios.WS_Datos_User.BuscarRequestBody Body;
        
        public BuscarRequest() {
        }
        
        public BuscarRequest(WS_Negocios.WS_Datos_User.BuscarRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class BuscarRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int id;
        
        public BuscarRequestBody() {
        }
        
        public BuscarRequestBody(int id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class BuscarResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="BuscarResponse", Namespace="http://tempuri.org/", Order=0)]
        public WS_Negocios.WS_Datos_User.BuscarResponseBody Body;
        
        public BuscarResponse() {
        }
        
        public BuscarResponse(WS_Negocios.WS_Datos_User.BuscarResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class BuscarResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WS_Negocios.WS_Datos_User.Personas[] BuscarResult;
        
        public BuscarResponseBody() {
        }
        
        public BuscarResponseBody(WS_Negocios.WS_Datos_User.Personas[] BuscarResult) {
            this.BuscarResult = BuscarResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface DatosSoapChannel : WS_Negocios.WS_Datos_User.DatosSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DatosSoapClient : System.ServiceModel.ClientBase<WS_Negocios.WS_Datos_User.DatosSoap>, WS_Negocios.WS_Datos_User.DatosSoap {
        
        public DatosSoapClient() {
        }
        
        public DatosSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DatosSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DatosSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DatosSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WS_Negocios.WS_Datos_User.insertarResponse WS_Negocios.WS_Datos_User.DatosSoap.insertar(WS_Negocios.WS_Datos_User.insertarRequest request) {
            return base.Channel.insertar(request);
        }
        
        public string insertar(WS_Negocios.WS_Datos_User.Personas personas) {
            WS_Negocios.WS_Datos_User.insertarRequest inValue = new WS_Negocios.WS_Datos_User.insertarRequest();
            inValue.Body = new WS_Negocios.WS_Datos_User.insertarRequestBody();
            inValue.Body.personas = personas;
            WS_Negocios.WS_Datos_User.insertarResponse retVal = ((WS_Negocios.WS_Datos_User.DatosSoap)(this)).insertar(inValue);
            return retVal.Body.insertarResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WS_Negocios.WS_Datos_User.insertarResponse> WS_Negocios.WS_Datos_User.DatosSoap.insertarAsync(WS_Negocios.WS_Datos_User.insertarRequest request) {
            return base.Channel.insertarAsync(request);
        }
        
        public System.Threading.Tasks.Task<WS_Negocios.WS_Datos_User.insertarResponse> insertarAsync(WS_Negocios.WS_Datos_User.Personas personas) {
            WS_Negocios.WS_Datos_User.insertarRequest inValue = new WS_Negocios.WS_Datos_User.insertarRequest();
            inValue.Body = new WS_Negocios.WS_Datos_User.insertarRequestBody();
            inValue.Body.personas = personas;
            return ((WS_Negocios.WS_Datos_User.DatosSoap)(this)).insertarAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WS_Negocios.WS_Datos_User.modificarResponse WS_Negocios.WS_Datos_User.DatosSoap.modificar(WS_Negocios.WS_Datos_User.modificarRequest request) {
            return base.Channel.modificar(request);
        }
        
        public string modificar(WS_Negocios.WS_Datos_User.Personas personas) {
            WS_Negocios.WS_Datos_User.modificarRequest inValue = new WS_Negocios.WS_Datos_User.modificarRequest();
            inValue.Body = new WS_Negocios.WS_Datos_User.modificarRequestBody();
            inValue.Body.personas = personas;
            WS_Negocios.WS_Datos_User.modificarResponse retVal = ((WS_Negocios.WS_Datos_User.DatosSoap)(this)).modificar(inValue);
            return retVal.Body.modificarResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WS_Negocios.WS_Datos_User.modificarResponse> WS_Negocios.WS_Datos_User.DatosSoap.modificarAsync(WS_Negocios.WS_Datos_User.modificarRequest request) {
            return base.Channel.modificarAsync(request);
        }
        
        public System.Threading.Tasks.Task<WS_Negocios.WS_Datos_User.modificarResponse> modificarAsync(WS_Negocios.WS_Datos_User.Personas personas) {
            WS_Negocios.WS_Datos_User.modificarRequest inValue = new WS_Negocios.WS_Datos_User.modificarRequest();
            inValue.Body = new WS_Negocios.WS_Datos_User.modificarRequestBody();
            inValue.Body.personas = personas;
            return ((WS_Negocios.WS_Datos_User.DatosSoap)(this)).modificarAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WS_Negocios.WS_Datos_User.EliminarResponse WS_Negocios.WS_Datos_User.DatosSoap.Eliminar(WS_Negocios.WS_Datos_User.EliminarRequest request) {
            return base.Channel.Eliminar(request);
        }
        
        public string Eliminar(int id) {
            WS_Negocios.WS_Datos_User.EliminarRequest inValue = new WS_Negocios.WS_Datos_User.EliminarRequest();
            inValue.Body = new WS_Negocios.WS_Datos_User.EliminarRequestBody();
            inValue.Body.id = id;
            WS_Negocios.WS_Datos_User.EliminarResponse retVal = ((WS_Negocios.WS_Datos_User.DatosSoap)(this)).Eliminar(inValue);
            return retVal.Body.EliminarResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WS_Negocios.WS_Datos_User.EliminarResponse> WS_Negocios.WS_Datos_User.DatosSoap.EliminarAsync(WS_Negocios.WS_Datos_User.EliminarRequest request) {
            return base.Channel.EliminarAsync(request);
        }
        
        public System.Threading.Tasks.Task<WS_Negocios.WS_Datos_User.EliminarResponse> EliminarAsync(int id) {
            WS_Negocios.WS_Datos_User.EliminarRequest inValue = new WS_Negocios.WS_Datos_User.EliminarRequest();
            inValue.Body = new WS_Negocios.WS_Datos_User.EliminarRequestBody();
            inValue.Body.id = id;
            return ((WS_Negocios.WS_Datos_User.DatosSoap)(this)).EliminarAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WS_Negocios.WS_Datos_User.MostrarResponse WS_Negocios.WS_Datos_User.DatosSoap.Mostrar(WS_Negocios.WS_Datos_User.MostrarRequest request) {
            return base.Channel.Mostrar(request);
        }
        
        public WS_Negocios.WS_Datos_User.Personas[] Mostrar() {
            WS_Negocios.WS_Datos_User.MostrarRequest inValue = new WS_Negocios.WS_Datos_User.MostrarRequest();
            inValue.Body = new WS_Negocios.WS_Datos_User.MostrarRequestBody();
            WS_Negocios.WS_Datos_User.MostrarResponse retVal = ((WS_Negocios.WS_Datos_User.DatosSoap)(this)).Mostrar(inValue);
            return retVal.Body.MostrarResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WS_Negocios.WS_Datos_User.MostrarResponse> WS_Negocios.WS_Datos_User.DatosSoap.MostrarAsync(WS_Negocios.WS_Datos_User.MostrarRequest request) {
            return base.Channel.MostrarAsync(request);
        }
        
        public System.Threading.Tasks.Task<WS_Negocios.WS_Datos_User.MostrarResponse> MostrarAsync() {
            WS_Negocios.WS_Datos_User.MostrarRequest inValue = new WS_Negocios.WS_Datos_User.MostrarRequest();
            inValue.Body = new WS_Negocios.WS_Datos_User.MostrarRequestBody();
            return ((WS_Negocios.WS_Datos_User.DatosSoap)(this)).MostrarAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WS_Negocios.WS_Datos_User.BuscarResponse WS_Negocios.WS_Datos_User.DatosSoap.Buscar(WS_Negocios.WS_Datos_User.BuscarRequest request) {
            return base.Channel.Buscar(request);
        }
        
        public WS_Negocios.WS_Datos_User.Personas[] Buscar(int id) {
            WS_Negocios.WS_Datos_User.BuscarRequest inValue = new WS_Negocios.WS_Datos_User.BuscarRequest();
            inValue.Body = new WS_Negocios.WS_Datos_User.BuscarRequestBody();
            inValue.Body.id = id;
            WS_Negocios.WS_Datos_User.BuscarResponse retVal = ((WS_Negocios.WS_Datos_User.DatosSoap)(this)).Buscar(inValue);
            return retVal.Body.BuscarResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WS_Negocios.WS_Datos_User.BuscarResponse> WS_Negocios.WS_Datos_User.DatosSoap.BuscarAsync(WS_Negocios.WS_Datos_User.BuscarRequest request) {
            return base.Channel.BuscarAsync(request);
        }
        
        public System.Threading.Tasks.Task<WS_Negocios.WS_Datos_User.BuscarResponse> BuscarAsync(int id) {
            WS_Negocios.WS_Datos_User.BuscarRequest inValue = new WS_Negocios.WS_Datos_User.BuscarRequest();
            inValue.Body = new WS_Negocios.WS_Datos_User.BuscarRequestBody();
            inValue.Body.id = id;
            return ((WS_Negocios.WS_Datos_User.DatosSoap)(this)).BuscarAsync(inValue);
        }
    }
}
