//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WS_Vista_Proc.WS_Negocios {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Usuario", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Usuario : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WS_Vista_Proc.WS_Negocios.ExtensionDataObject ExtensionData1Field;
        
        private int idField;
        
        private int ID_UsuarioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ApellidosField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CorreoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string telefonoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="ExtensionData", EmitDefaultValue=false)]
        public WS_Vista_Proc.WS_Negocios.ExtensionDataObject ExtensionData1 {
            get {
                return this.ExtensionData1Field;
            }
            set {
                if ((object.ReferenceEquals(this.ExtensionData1Field, value) != true)) {
                    this.ExtensionData1Field = value;
                    this.RaisePropertyChanged("ExtensionData1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public int ID_Usuario {
            get {
                return this.ID_UsuarioField;
            }
            set {
                if ((this.ID_UsuarioField.Equals(value) != true)) {
                    this.ID_UsuarioField = value;
                    this.RaisePropertyChanged("ID_Usuario");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string Apellidos {
            get {
                return this.ApellidosField;
            }
            set {
                if ((object.ReferenceEquals(this.ApellidosField, value) != true)) {
                    this.ApellidosField = value;
                    this.RaisePropertyChanged("Apellidos");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string Correo {
            get {
                return this.CorreoField;
            }
            set {
                if ((object.ReferenceEquals(this.CorreoField, value) != true)) {
                    this.CorreoField = value;
                    this.RaisePropertyChanged("Correo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string telefono {
            get {
                return this.telefonoField;
            }
            set {
                if ((object.ReferenceEquals(this.telefonoField, value) != true)) {
                    this.telefonoField = value;
                    this.RaisePropertyChanged("telefono");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ExtensionDataObject", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class ExtensionDataObject : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WS_Negocios.NegociosUsuSoap")]
    public interface NegociosUsuSoap {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento personas del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Insertar", ReplyAction="*")]
        WS_Vista_Proc.WS_Negocios.InsertarResponse Insertar(WS_Vista_Proc.WS_Negocios.InsertarRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Insertar", ReplyAction="*")]
        System.Threading.Tasks.Task<WS_Vista_Proc.WS_Negocios.InsertarResponse> InsertarAsync(WS_Vista_Proc.WS_Negocios.InsertarRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento personas del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Modificar", ReplyAction="*")]
        WS_Vista_Proc.WS_Negocios.ModificarResponse Modificar(WS_Vista_Proc.WS_Negocios.ModificarRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Modificar", ReplyAction="*")]
        System.Threading.Tasks.Task<WS_Vista_Proc.WS_Negocios.ModificarResponse> ModificarAsync(WS_Vista_Proc.WS_Negocios.ModificarRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento EliminarResult del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Eliminar", ReplyAction="*")]
        WS_Vista_Proc.WS_Negocios.EliminarResponse Eliminar(WS_Vista_Proc.WS_Negocios.EliminarRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Eliminar", ReplyAction="*")]
        System.Threading.Tasks.Task<WS_Vista_Proc.WS_Negocios.EliminarResponse> EliminarAsync(WS_Vista_Proc.WS_Negocios.EliminarRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento BuscarResult del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Buscar", ReplyAction="*")]
        WS_Vista_Proc.WS_Negocios.BuscarResponse Buscar(WS_Vista_Proc.WS_Negocios.BuscarRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Buscar", ReplyAction="*")]
        System.Threading.Tasks.Task<WS_Vista_Proc.WS_Negocios.BuscarResponse> BuscarAsync(WS_Vista_Proc.WS_Negocios.BuscarRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento MostrarResult del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Mostrar", ReplyAction="*")]
        WS_Vista_Proc.WS_Negocios.MostrarResponse Mostrar(WS_Vista_Proc.WS_Negocios.MostrarRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Mostrar", ReplyAction="*")]
        System.Threading.Tasks.Task<WS_Vista_Proc.WS_Negocios.MostrarResponse> MostrarAsync(WS_Vista_Proc.WS_Negocios.MostrarRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InsertarRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Insertar", Namespace="http://tempuri.org/", Order=0)]
        public WS_Vista_Proc.WS_Negocios.InsertarRequestBody Body;
        
        public InsertarRequest() {
        }
        
        public InsertarRequest(WS_Vista_Proc.WS_Negocios.InsertarRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class InsertarRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WS_Vista_Proc.WS_Negocios.Usuario personas;
        
        public InsertarRequestBody() {
        }
        
        public InsertarRequestBody(WS_Vista_Proc.WS_Negocios.Usuario personas) {
            this.personas = personas;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InsertarResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InsertarResponse", Namespace="http://tempuri.org/", Order=0)]
        public WS_Vista_Proc.WS_Negocios.InsertarResponseBody Body;
        
        public InsertarResponse() {
        }
        
        public InsertarResponse(WS_Vista_Proc.WS_Negocios.InsertarResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class InsertarResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string InsertarResult;
        
        public InsertarResponseBody() {
        }
        
        public InsertarResponseBody(string InsertarResult) {
            this.InsertarResult = InsertarResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ModificarRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Modificar", Namespace="http://tempuri.org/", Order=0)]
        public WS_Vista_Proc.WS_Negocios.ModificarRequestBody Body;
        
        public ModificarRequest() {
        }
        
        public ModificarRequest(WS_Vista_Proc.WS_Negocios.ModificarRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ModificarRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WS_Vista_Proc.WS_Negocios.Usuario personas;
        
        public ModificarRequestBody() {
        }
        
        public ModificarRequestBody(WS_Vista_Proc.WS_Negocios.Usuario personas) {
            this.personas = personas;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ModificarResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ModificarResponse", Namespace="http://tempuri.org/", Order=0)]
        public WS_Vista_Proc.WS_Negocios.ModificarResponseBody Body;
        
        public ModificarResponse() {
        }
        
        public ModificarResponse(WS_Vista_Proc.WS_Negocios.ModificarResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ModificarResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ModificarResult;
        
        public ModificarResponseBody() {
        }
        
        public ModificarResponseBody(string ModificarResult) {
            this.ModificarResult = ModificarResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class EliminarRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Eliminar", Namespace="http://tempuri.org/", Order=0)]
        public WS_Vista_Proc.WS_Negocios.EliminarRequestBody Body;
        
        public EliminarRequest() {
        }
        
        public EliminarRequest(WS_Vista_Proc.WS_Negocios.EliminarRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class EliminarRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int id;
        
        public EliminarRequestBody() {
        }
        
        public EliminarRequestBody(int id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class EliminarResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="EliminarResponse", Namespace="http://tempuri.org/", Order=0)]
        public WS_Vista_Proc.WS_Negocios.EliminarResponseBody Body;
        
        public EliminarResponse() {
        }
        
        public EliminarResponse(WS_Vista_Proc.WS_Negocios.EliminarResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class EliminarResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string EliminarResult;
        
        public EliminarResponseBody() {
        }
        
        public EliminarResponseBody(string EliminarResult) {
            this.EliminarResult = EliminarResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class BuscarRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Buscar", Namespace="http://tempuri.org/", Order=0)]
        public WS_Vista_Proc.WS_Negocios.BuscarRequestBody Body;
        
        public BuscarRequest() {
        }
        
        public BuscarRequest(WS_Vista_Proc.WS_Negocios.BuscarRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class BuscarRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int id;
        
        public BuscarRequestBody() {
        }
        
        public BuscarRequestBody(int id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class BuscarResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="BuscarResponse", Namespace="http://tempuri.org/", Order=0)]
        public WS_Vista_Proc.WS_Negocios.BuscarResponseBody Body;
        
        public BuscarResponse() {
        }
        
        public BuscarResponse(WS_Vista_Proc.WS_Negocios.BuscarResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class BuscarResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WS_Vista_Proc.WS_Negocios.Usuario[] BuscarResult;
        
        public BuscarResponseBody() {
        }
        
        public BuscarResponseBody(WS_Vista_Proc.WS_Negocios.Usuario[] BuscarResult) {
            this.BuscarResult = BuscarResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class MostrarRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Mostrar", Namespace="http://tempuri.org/", Order=0)]
        public WS_Vista_Proc.WS_Negocios.MostrarRequestBody Body;
        
        public MostrarRequest() {
        }
        
        public MostrarRequest(WS_Vista_Proc.WS_Negocios.MostrarRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class MostrarRequestBody {
        
        public MostrarRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class MostrarResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="MostrarResponse", Namespace="http://tempuri.org/", Order=0)]
        public WS_Vista_Proc.WS_Negocios.MostrarResponseBody Body;
        
        public MostrarResponse() {
        }
        
        public MostrarResponse(WS_Vista_Proc.WS_Negocios.MostrarResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class MostrarResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WS_Vista_Proc.WS_Negocios.Usuario[] MostrarResult;
        
        public MostrarResponseBody() {
        }
        
        public MostrarResponseBody(WS_Vista_Proc.WS_Negocios.Usuario[] MostrarResult) {
            this.MostrarResult = MostrarResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface NegociosUsuSoapChannel : WS_Vista_Proc.WS_Negocios.NegociosUsuSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class NegociosUsuSoapClient : System.ServiceModel.ClientBase<WS_Vista_Proc.WS_Negocios.NegociosUsuSoap>, WS_Vista_Proc.WS_Negocios.NegociosUsuSoap {
        
        public NegociosUsuSoapClient() {
        }
        
        public NegociosUsuSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public NegociosUsuSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public NegociosUsuSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public NegociosUsuSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WS_Vista_Proc.WS_Negocios.InsertarResponse WS_Vista_Proc.WS_Negocios.NegociosUsuSoap.Insertar(WS_Vista_Proc.WS_Negocios.InsertarRequest request) {
            return base.Channel.Insertar(request);
        }
        
        public string Insertar(WS_Vista_Proc.WS_Negocios.Usuario personas) {
            WS_Vista_Proc.WS_Negocios.InsertarRequest inValue = new WS_Vista_Proc.WS_Negocios.InsertarRequest();
            inValue.Body = new WS_Vista_Proc.WS_Negocios.InsertarRequestBody();
            inValue.Body.personas = personas;
            WS_Vista_Proc.WS_Negocios.InsertarResponse retVal = ((WS_Vista_Proc.WS_Negocios.NegociosUsuSoap)(this)).Insertar(inValue);
            return retVal.Body.InsertarResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WS_Vista_Proc.WS_Negocios.InsertarResponse> WS_Vista_Proc.WS_Negocios.NegociosUsuSoap.InsertarAsync(WS_Vista_Proc.WS_Negocios.InsertarRequest request) {
            return base.Channel.InsertarAsync(request);
        }
        
        public System.Threading.Tasks.Task<WS_Vista_Proc.WS_Negocios.InsertarResponse> InsertarAsync(WS_Vista_Proc.WS_Negocios.Usuario personas) {
            WS_Vista_Proc.WS_Negocios.InsertarRequest inValue = new WS_Vista_Proc.WS_Negocios.InsertarRequest();
            inValue.Body = new WS_Vista_Proc.WS_Negocios.InsertarRequestBody();
            inValue.Body.personas = personas;
            return ((WS_Vista_Proc.WS_Negocios.NegociosUsuSoap)(this)).InsertarAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WS_Vista_Proc.WS_Negocios.ModificarResponse WS_Vista_Proc.WS_Negocios.NegociosUsuSoap.Modificar(WS_Vista_Proc.WS_Negocios.ModificarRequest request) {
            return base.Channel.Modificar(request);
        }
        
        public string Modificar(WS_Vista_Proc.WS_Negocios.Usuario personas) {
            WS_Vista_Proc.WS_Negocios.ModificarRequest inValue = new WS_Vista_Proc.WS_Negocios.ModificarRequest();
            inValue.Body = new WS_Vista_Proc.WS_Negocios.ModificarRequestBody();
            inValue.Body.personas = personas;
            WS_Vista_Proc.WS_Negocios.ModificarResponse retVal = ((WS_Vista_Proc.WS_Negocios.NegociosUsuSoap)(this)).Modificar(inValue);
            return retVal.Body.ModificarResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WS_Vista_Proc.WS_Negocios.ModificarResponse> WS_Vista_Proc.WS_Negocios.NegociosUsuSoap.ModificarAsync(WS_Vista_Proc.WS_Negocios.ModificarRequest request) {
            return base.Channel.ModificarAsync(request);
        }
        
        public System.Threading.Tasks.Task<WS_Vista_Proc.WS_Negocios.ModificarResponse> ModificarAsync(WS_Vista_Proc.WS_Negocios.Usuario personas) {
            WS_Vista_Proc.WS_Negocios.ModificarRequest inValue = new WS_Vista_Proc.WS_Negocios.ModificarRequest();
            inValue.Body = new WS_Vista_Proc.WS_Negocios.ModificarRequestBody();
            inValue.Body.personas = personas;
            return ((WS_Vista_Proc.WS_Negocios.NegociosUsuSoap)(this)).ModificarAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WS_Vista_Proc.WS_Negocios.EliminarResponse WS_Vista_Proc.WS_Negocios.NegociosUsuSoap.Eliminar(WS_Vista_Proc.WS_Negocios.EliminarRequest request) {
            return base.Channel.Eliminar(request);
        }
        
        public string Eliminar(int id) {
            WS_Vista_Proc.WS_Negocios.EliminarRequest inValue = new WS_Vista_Proc.WS_Negocios.EliminarRequest();
            inValue.Body = new WS_Vista_Proc.WS_Negocios.EliminarRequestBody();
            inValue.Body.id = id;
            WS_Vista_Proc.WS_Negocios.EliminarResponse retVal = ((WS_Vista_Proc.WS_Negocios.NegociosUsuSoap)(this)).Eliminar(inValue);
            return retVal.Body.EliminarResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WS_Vista_Proc.WS_Negocios.EliminarResponse> WS_Vista_Proc.WS_Negocios.NegociosUsuSoap.EliminarAsync(WS_Vista_Proc.WS_Negocios.EliminarRequest request) {
            return base.Channel.EliminarAsync(request);
        }
        
        public System.Threading.Tasks.Task<WS_Vista_Proc.WS_Negocios.EliminarResponse> EliminarAsync(int id) {
            WS_Vista_Proc.WS_Negocios.EliminarRequest inValue = new WS_Vista_Proc.WS_Negocios.EliminarRequest();
            inValue.Body = new WS_Vista_Proc.WS_Negocios.EliminarRequestBody();
            inValue.Body.id = id;
            return ((WS_Vista_Proc.WS_Negocios.NegociosUsuSoap)(this)).EliminarAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WS_Vista_Proc.WS_Negocios.BuscarResponse WS_Vista_Proc.WS_Negocios.NegociosUsuSoap.Buscar(WS_Vista_Proc.WS_Negocios.BuscarRequest request) {
            return base.Channel.Buscar(request);
        }
        
        public WS_Vista_Proc.WS_Negocios.Usuario[] Buscar(int id) {
            WS_Vista_Proc.WS_Negocios.BuscarRequest inValue = new WS_Vista_Proc.WS_Negocios.BuscarRequest();
            inValue.Body = new WS_Vista_Proc.WS_Negocios.BuscarRequestBody();
            inValue.Body.id = id;
            WS_Vista_Proc.WS_Negocios.BuscarResponse retVal = ((WS_Vista_Proc.WS_Negocios.NegociosUsuSoap)(this)).Buscar(inValue);
            return retVal.Body.BuscarResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WS_Vista_Proc.WS_Negocios.BuscarResponse> WS_Vista_Proc.WS_Negocios.NegociosUsuSoap.BuscarAsync(WS_Vista_Proc.WS_Negocios.BuscarRequest request) {
            return base.Channel.BuscarAsync(request);
        }
        
        public System.Threading.Tasks.Task<WS_Vista_Proc.WS_Negocios.BuscarResponse> BuscarAsync(int id) {
            WS_Vista_Proc.WS_Negocios.BuscarRequest inValue = new WS_Vista_Proc.WS_Negocios.BuscarRequest();
            inValue.Body = new WS_Vista_Proc.WS_Negocios.BuscarRequestBody();
            inValue.Body.id = id;
            return ((WS_Vista_Proc.WS_Negocios.NegociosUsuSoap)(this)).BuscarAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WS_Vista_Proc.WS_Negocios.MostrarResponse WS_Vista_Proc.WS_Negocios.NegociosUsuSoap.Mostrar(WS_Vista_Proc.WS_Negocios.MostrarRequest request) {
            return base.Channel.Mostrar(request);
        }
        
        public WS_Vista_Proc.WS_Negocios.Usuario[] Mostrar() {
            WS_Vista_Proc.WS_Negocios.MostrarRequest inValue = new WS_Vista_Proc.WS_Negocios.MostrarRequest();
            inValue.Body = new WS_Vista_Proc.WS_Negocios.MostrarRequestBody();
            WS_Vista_Proc.WS_Negocios.MostrarResponse retVal = ((WS_Vista_Proc.WS_Negocios.NegociosUsuSoap)(this)).Mostrar(inValue);
            return retVal.Body.MostrarResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WS_Vista_Proc.WS_Negocios.MostrarResponse> WS_Vista_Proc.WS_Negocios.NegociosUsuSoap.MostrarAsync(WS_Vista_Proc.WS_Negocios.MostrarRequest request) {
            return base.Channel.MostrarAsync(request);
        }
        
        public System.Threading.Tasks.Task<WS_Vista_Proc.WS_Negocios.MostrarResponse> MostrarAsync() {
            WS_Vista_Proc.WS_Negocios.MostrarRequest inValue = new WS_Vista_Proc.WS_Negocios.MostrarRequest();
            inValue.Body = new WS_Vista_Proc.WS_Negocios.MostrarRequestBody();
            return ((WS_Vista_Proc.WS_Negocios.NegociosUsuSoap)(this)).MostrarAsync(inValue);
        }
    }
}
